version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s.%(msecs)03dZ %(levelname)5s %(process)d --- [%(threadName)s] %(name)s : %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: edps.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [ console,file ]
